version: "3.5"

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: charge_customer_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  customer:
    image: renegotiation/customer
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/charge_customer_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    depends_on:
      - db

  colletion-email:
    image: renegotiation/collection-email
    ports:
      - "8081:8081"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/charge_customer_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      CUSTOMER_API_URL: customer:8080
    depends_on:
      - db