version: "3.5"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: charge_customer_db

  customer:
    image: renegotiation/customer
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://localhost:3306/customers_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_DATABASE: customers_db
    depends_on:
      - mysql

  colletion-email:
    image: renegotiation/collection-email
    ports:
      - "8081:8081"
    environment:
      MYSQL_URL: jdbc:mysql://localhost:3306/collection_emails_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_DATABASE: collection_emails_bd
      CUSTOMER_API_URL: localhost:8080
    depends_on:
      - mysql