version: "3.5"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_DB: charge_customer_db

  customer:
    image: renegotiation/customer
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:mysql://localhost:3306/charge_customer_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
    depends_on:
      - mysql

  colletion-email:
    image: renegotiation/collection-email
    ports:
      - "8081:8081"
    environment:
      MYSQL_URL: jdbc:mysql://localhost:3306/charge_customer_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      CUSTOMER_API_URL: localhost:8080
    depends_on:
      - mysql